# Render Blueprint for Task Management App
# This file can be used to deploy both services at once

services:
  # Backend API Service
  - type: web
    name: task-management-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_USER
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 5432
      - key: JWT_SECRET
        sync: false

  # Frontend Static Site
  - type: web
    name: task-management-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: task-management-backend
          property: host
